// <auto-generated />
namespace ChangeManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SeedJobRolesTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedJobRolesTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201901110216586_SeedJobRolesTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
